### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by Acen28** [pr0me/SAFIREFUZZ#3]
When I use the following command to compile
 cargo build --release --target armv7-unknown-linux-gnueabihf
It interrupted and show:
error:package 'regex-automata v0.4.9' cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.62.0-nightly

Please help

**Comment by Acen28** [comment]
I doubted that it is caused by the rust-toolchain file, but I don't know how to change it.

**Comment by pr0me** [comment]
Hey, thanks for reaching out and sorry that I didn't see your issue for so long.
Please see #4 for a discussion on this and try out the most recent commit.
